# Default configuration for training and augmentation

# Dataset configurations
dataset:
  name: "dataset1"
  path: "data/raw"
  processed_path: "data/processed"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Model configurations
model:
  type: "vae"
  latent_dim: 128
  hidden_dims: [32, 64, 128, 256]
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 100

# Augmentation configurations
augmentation:
  enabled: true
  methods:
    - name: "gaussian_noise"
      probability: 0.5
      params:
        mean: 0.0
        std: 0.1
    - name: "time_warp"
      probability: 0.3
      params:
        magnitude: 0.2

# Training configurations
training:
  device: "cuda"
  seed: 42
  num_workers: 4
  checkpoint_frequency: 10
  log_frequency: 100

# Logging configurations
logging:
  level: "INFO"
  save_dir: "experiments" 